#ifndef ZEPHIR_VERSION_HPP_
#define ZEPHIR_VERSION_HPP_

#define ZEPHIR_VERSION_MAJOR 1
#define ZEPHIR_VERSION_MINOR 0
#define ZEPHIR_VERSION_PATCH 0

#define ZEPHIR_VERSION_ID \
	(((ZEPHIR_VERSION_MAJOR)*10000000) + ((ZEPHIR_VERSION_MINOR)*100000) \
	 + (ZEPHIR_VERSION_PATCH))

#endif // ZEPHIR_VERSION_HPP_
