#!/usr/bin/env bash

# This file is part of the Zephir.
#
# (c) Phalcon Team <team@zephir-lang.com>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.
#
# Initially written by Alexander Haase <alexander.haase@rwth-aachen.de>
# Adapted by Serghei Iakovlev <egrep@protonmail.ch>

[ -z "${LLVM_COV_EXE:-}" ] && {
  >&2 echo "The LLVM_COV_EXE environment variable is not set. Aborting."
  exit 1
}

# Get LLVM version to find out.
LLVM_VERSION=$($LLVM_COV_EXE -version | grep -i "LLVM version" \
	| sed "s/^\([A-Za-z ]*\)\([0-9]*\).\([0-9]*\).*$/\2.\3/g")

[ "$1" = "-v" ] && {
	echo "llvm-cov-wrapper $LLVM_VERSION"
	exit 0
}

[ "$1" = "--help" ] && {
  exec "$LLVM_COV_EXE" gcov --help
  exit 0
}

if [ -n "$LLVM_VERSION" ]
then
	MAJOR=$(echo "$LLVM_VERSION" | cut -d'.' -f1)
	MINOR=$(echo "$LLVM_VERSION" | cut -d'.' -f2)

	if [ "$MAJOR" -eq 3 ] && [ "$MINOR" -le 4 ]
	then
		if [ -f "$1" ]
		then
			filename=$(basename "$1")
			extension="${filename##*.}"

			case "$extension" in
				"gcno") exec "$LLVM_COV_EXE" --gcno="$1" ;;
				"gcda") exec "$LLVM_COV_EXE" --gcda="$1" ;;
			esac
		fi
	fi

	if [ "$MAJOR" -eq 3 ] && [ "$MINOR" -le 5 ]
	then
		exec "$LLVM_COV_EXE" "$@"
	fi
fi

exec "$LLVM_COV_EXE" gcov "$@"
