name: build

on: [push, pull_request]

jobs:
  simple_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup Prerequisites
      run: |
        sudo apt-get update --quiet --yes 1>/dev/null
        sudo apt-get install --no-install-recommends --quiet --yes \
            lcov          \
            libspdlog-dev \
            libyaml-cpp-dev

    - name: Configure
      run: |
        cmake                         \
            -S .                      \
            -Bbuild                   \
            -DCMAKE_BUILD_TYPE=Debug  \
            -DZEPHIR_BUILD_TESTING=ON \
            -DENABLE_ALL_WARNINGS=ON  \
            -DCODE_COVERAGE=ON        \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        echo ::set-env name=ZEPHIR_TESTS_ROOT::${GITHUB_WORKSPACE}/tests

    - name: Build
      run: cmake --build build -j 10

    - name: Run Tests
      run: |
          cd build
          ctest --output-on-failure

    - name: Generate code coverage report
      run: |
          cd build
          make ccov-all

    - name: Upload code coverage report
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
